variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - hugo

hugo:
  stage: hugo
  image: monachus/hugo
  script:
  - apt-get update
  - apt-get install -y gnupg
  - curl -sL https://deb.nodesource.com/setup_8.x | bash -
  - apt-get install -y nodejs
  - npm install
  - cd themes/hugo-sui-blog; npm install
  - hugo
  artifacts:
    paths:
    - public
  only:
  - master

