Paginate: 15
disqusShortname: w96k
relativeURLs: true
theme: hugo-sui-blog
title: "@w96k"
languageCode: "ru-ru"
copyright: "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."
author:
  name: Mikhail Kirillov
  email: w96k.ru@gmail.com
menu:
  main:
  - identifier: posts
    name: Посты
    title: Посты
    url: /posts/
  - identifier: pages
    name: Страницы
    title: Страницы
    url: /pages/
    parent:
    - identifier: about
      name: Обо мне
      title: Обо мне
      url: about
params:
  mainSection: ["posts"]
  comments: true
  about:
    - Dev
    - Otaku
    - Gamer
  social:
    - text: Github
      icon: github
      link: https://github.com/w96k
      target: "_blank"
      color: white
    - text: Telegram
      icon: telegram
      link: https://t.me/w96k_log
      target: "_blank"
      color: blue
    - text: Twitter
      icon: twitter
      link: https://twitter.com/w96kz
      color: twitter
  bonsai:
    vars:
      - title
      - summary
      - date
      - publishdate
      - expirydate
      - permalink
    params:
      - categories
      - tags

outputs:
  home:
    - HTML
    - RSS
    - Bonsai
outputFormats:
  Bonsai:
    baseName: bonsai
    isPlainText: true
    mediaType: application/json
    notAlternative: true
