#+HUGO_BASE_DIR: ../
#+HUGO_SECTION: pages

#+HUGO_WEIGHT: auto
#+HUGO_AUTO_SET_LASTMOD: t

* @w96k
  В этом файле находятся все страницы
** Обо мне
   :PROPERTIES:
   :EXPORT_FILE_NAME: about
   :EXPORT_HUGO_MENU: :menu "main" :parent "pages"
   :EXPORT_DATE: 2018-10-31
   :EXPORT_HUGO_CUSTOM_FRONT_MATTER: :greeting Привет! 👋
   :EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :type _static
   :EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :page _static/about.html
   :EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :cover /ava.jpg
   :EXPORT_HUGO_CUSTOM_FRONT_MATTER+: :ava /ava.jpg
   :END:
   Я — Михаил. Занимаюсь фулл-стек разработкой. Создаю сайты как с
   использованием  шаблонизатора, так и с использованием
   SPA-фреймворков. Пишу cli-утилиты, создаю API, настраиваю CI.

   В основном использую Node.js и экосистему, построенную вокруг
   него. Не брезгаю использовать другие языки и
   инструменты. Интересно использование Clojure,
   Go, Rust.

   Учусь на [[https://ru.hexlet.io/u/w96k][*Hexlet*]]. Читаю на [[https://www.goodreads.com/user/show/71049684-mikhail-kirillov][*Goodreads*]]. Пилю на [[https://github.com/w96k/][*Github*]].
