#+Title: Libreboot X200T

* Libreboot X200T

Вот уже несколько месяцев я использую Thinkpad X200T в качестве
основной рабочей машины. Этот ноутбук убивает желание иметь дома
настольный комьпютер и учит ценить ограниченный вычислительный
ресурс. После покупки я полностью отказался от использования мыши. Его
удобно таскать с собой, он быстро загружается и держит заряд 4 часа.

** Libreboot

   Libreboot — свободная альтернатива BIOS и UEFI. Многие любят
   свободный софт, но исторически сложилось так, что программы,
   отвечающие за инициализацию системы полностью закрыты.

   Активисты свободного ПО создали открытую реализацию BIOS / UEFI,
   которая помимо того, что открыта для всех желающих и расширяема, так
   еще работает быстрее встроенных закрытых систем. Одна из таких
   реализаций называется Coreboot, она содержит проприоритарные блобы от
   производителей железа, а Libreboot является версией Coreboot без
   блобов и входит в проект GNU. Libreboot не является форком Coreboot,
   это отдельная поставка Coreboot.
